<a href="https://colab.research.google.com/github/25wh1a0564-ai/NASSCOM/blob/main/Week2/Pandas_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

print("\n--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---")

# 1.1 Create a Pandas Series
s1_1 = pd.Series([10, 20, 30, 40, 50])
print("\nSeries s1_1:")
print(s1_1)

# 1.2 Create a 3x4 NumPy array with random integers between 1 and 100
np_array1_2 = np.random.randint(1, 101, size=(3, 4))
print("\nNumPy Array np_array1_2:")
print(np_array1_2)

# 1.3 Convert NumPy array into a Pandas DataFrame
df1_3 = pd.DataFrame(np_array1_2, columns=['A', 'B', 'C', 'D'])
print("\nDataFrame df1_3:")
print(df1_3)


--- Task 1: Basic Pandas Functions and Converting Arrays to DataFrames ---

Series s1_1:
0    10
1    20
2    30
3    40
4    50
dtype: int64

NumPy Array np_array1_2:
[[48 62 31 93]
 [52 44 87 86]
 [62 93 70 93]]

DataFrame df1_3:
    A   B   C   D
0  48  62  31  93
1  52  44  87  86
2  62  93  70  93


In [2]:
import pandas as pd
import numpy as np

print("\n--- Task 2: Synthetic Data Generation for Practice ---")

# Set seed for reproducible results
np.random.seed(1)

# Create 100 dates
dates = pd.date_range(start='2023-01-01', end='2023-04-09', periods=100)

# Create DataFrame
df_sales = pd.DataFrame({
    'Date': dates,
    'Region': np.random.choice(['East', 'West', 'North', 'South'], size=100),
    'Product': np.random.choice(['Laptop', 'Mouse', 'Keyboard', 'Monitor'], size=100),
    'Sales': np.random.randint(100, 1001, size=100),
    'Quantity': np.random.randint(1, 11, size=100)
})

# Introduce NaN values
sales_nan = np.random.choice(df_sales.index, size=5, replace=False)
quantity_nan = np.random.choice(df_sales.index, size=3, replace=False)

df_sales.loc[sales_nan, 'Sales'] = np.nan
df_sales.loc[quantity_nan, 'Quantity'] = np.nan

# Display the DataFrame
print("\nSales DataFrame:")
print(df_sales)


--- Task 2: Synthetic Data Generation for Practice ---

Sales DataFrame:
                            Date Region   Product  Sales  Quantity
0  2023-01-01 00:00:00.000000000   West     Mouse  120.0       7.0
1  2023-01-01 23:45:27.272727272  South     Mouse  730.0       8.0
2  2023-01-02 23:30:54.545454545   East   Monitor  378.0       4.0
3  2023-01-03 23:16:21.818181818   East  Keyboard    NaN       6.0
4  2023-01-04 23:01:49.090909090  South    Laptop  726.0       4.0
..                           ...    ...       ...    ...       ...
95 2023-04-05 00:58:10.909090910  North  Keyboard  599.0       7.0
96 2023-04-06 00:43:38.181818182  South   Monitor  887.0       4.0
97 2023-04-07 00:29:05.454545455   West     Mouse  351.0       1.0
98 2023-04-08 00:14:32.727272728   East     Mouse  766.0       7.0
99 2023-04-09 00:00:00.000000000  South  Keyboard  335.0       5.0

[100 rows x 5 columns]


In [3]:
# Task 3: Indexing and Slicing in DataFrames
print("\n--- Task 3: Indexing and Slicing in DataFrames ---")

# 3.1 Select Region and Sales columns
df3_1 = df_sales[['Region', 'Sales']]
print("\n3.1 Region and Sales:")
print(df3_1)

# 3.2 Select rows where Product is Laptop
df3_2 = df_sales[df_sales['Product'] == 'Laptop']
print("\n3.2 Product = Laptop:")
print(df3_2)

# 3.3 Select rows where Region is East AND Sales > 500
df3_3 = df_sales[
    (df_sales['Region'] == 'East') &
    (df_sales['Sales'] > 500)
]
print("\n3.3 East and Sales > 500:")
print(df3_3)

# 3.4 Select Sales value for the first Monitor
monitor_rows = df_sales[df_sales['Product'] == 'Monitor']

# Using .loc
first_monitor_index = monitor_rows.index[0]
val3_4 = df_sales.loc[first_monitor_index, 'Sales']

# Using .iloc
val3_4_iloc = monitor_rows.iloc[0]['Sales']

print("\n3.4 First Monitor Sales using .loc:", val3_4)
print("First Monitor Sales using .iloc:", val3_4_iloc)


--- Task 3: Indexing and Slicing in DataFrames ---

3.1 Region and Sales:
   Region  Sales
0    West  120.0
1   South  730.0
2    East  378.0
3    East    NaN
4   South  726.0
..    ...    ...
95  North  599.0
96  South  887.0
97   West  351.0
98   East  766.0
99  South  335.0

[100 rows x 2 columns]

3.2 Product = Laptop:
                            Date Region Product  Sales  Quantity
4  2023-01-04 23:01:49.090909090  South  Laptop  726.0       4.0
5  2023-01-05 22:47:16.363636363   West  Laptop  709.0       3.0
15 2023-01-15 20:21:49.090909091   East  Laptop  331.0       8.0
19 2023-01-19 19:23:38.181818182   East  Laptop    NaN       1.0
20 2023-01-20 19:09:05.454545454  North  Laptop  241.0       3.0
27 2023-01-27 17:27:16.363636364   East  Laptop  636.0       2.0
28 2023-01-28 17:12:43.636363636   West  Laptop  237.0       8.0
32 2023-02-01 16:14:32.727272727  South  Laptop  425.0       7.0
36 2023-02-05 15:16:21.818181818  South  Laptop  121.0       7.0
42 2023-02-11 13:49:05.4

In [4]:
# Task 4: Data Cleaning (Handling Missing Values)
print("\n--- Task 4: Data Cleaning (Handling Missing Values) ---")

# 4.1 Check missing values in each column
missing_counts4_1 = df_sales.isnull().sum()

print("\n4.1 Missing values:")
print(missing_counts4_1)


# 4.2 Fill missing Sales values with the mean
df4_2_filled = df_sales.copy()

sales_mean = df4_2_filled['Sales'].mean()
df4_2_filled['Sales'] = df4_2_filled['Sales'].fillna(sales_mean)

print("\n4.2 DataFrame after filling missing Sales:")
print(df4_2_filled)


# 4.3 Drop rows with any missing values
df4_3_dropped = df_sales.dropna()

print("\n4.3 DataFrame after dropping rows with missing values:")
print(df4_3_dropped)



--- Task 4: Data Cleaning (Handling Missing Values) ---

4.1 Missing values:
Date        0
Region      0
Product     0
Sales       5
Quantity    3
dtype: int64

4.2 DataFrame after filling missing Sales:
                            Date Region   Product       Sales  Quantity
0  2023-01-01 00:00:00.000000000   West     Mouse  120.000000       7.0
1  2023-01-01 23:45:27.272727272  South     Mouse  730.000000       8.0
2  2023-01-02 23:30:54.545454545   East   Monitor  378.000000       4.0
3  2023-01-03 23:16:21.818181818   East  Keyboard  528.621053       6.0
4  2023-01-04 23:01:49.090909090  South    Laptop  726.000000       4.0
..                           ...    ...       ...         ...       ...
95 2023-04-05 00:58:10.909090910  North  Keyboard  599.000000       7.0
96 2023-04-06 00:43:38.181818182  South   Monitor  887.000000       4.0
97 2023-04-07 00:29:05.454545455   West     Mouse  351.000000       1.0
98 2023-04-08 00:14:32.727272728   East     Mouse  766.000000       7.0
99 

In [6]:
# Task 5: Data Manipulation (Columns, Sorting, Grouping)
print("\n--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---")

# 5.1 Create Total_Revenue column
df_sales['Total_Revenue'] = df_sales['Sales'] * df_sales['Quantity']

print("\n5.1 Total Revenue:")
print(df_sales)


# 5.2 Sort by Date ascending, then Sales descending
df5_2_sorted = df_sales.sort_values(
    by=['Date', 'Sales'],
    ascending=[True, False]
)

print("\n5.2 Sorted DataFrame:")
print(df5_2_sorted)


# 5.3 Group by Region and calculate sum of Sales and Quantity
df5_3_grouped_region = df_sales.groupby('Region')[['Sales', 'Quantity']].sum()

print("\n5.3 Grouped by Region:")
print(df5_3_grouped_region)


# 5.4 Group by Product and calculate average Sales
df5_4_grouped_product = df_sales.groupby('Product')['Sales'].mean()

print("\n5.4 Average Sales by Product:")
print(df5_4_grouped_product)



--- Task 5: Data Manipulation (Columns, Sorting, Grouping) ---

5.1 Total Revenue:
                            Date Region   Product  Sales  Quantity  \
0  2023-01-01 00:00:00.000000000   West     Mouse  120.0       7.0   
1  2023-01-01 23:45:27.272727272  South     Mouse  730.0       8.0   
2  2023-01-02 23:30:54.545454545   East   Monitor  378.0       4.0   
3  2023-01-03 23:16:21.818181818   East  Keyboard    NaN       6.0   
4  2023-01-04 23:01:49.090909090  South    Laptop  726.0       4.0   
..                           ...    ...       ...    ...       ...   
95 2023-04-05 00:58:10.909090910  North  Keyboard  599.0       7.0   
96 2023-04-06 00:43:38.181818182  South   Monitor  887.0       4.0   
97 2023-04-07 00:29:05.454545455   West     Mouse  351.0       1.0   
98 2023-04-08 00:14:32.727272728   East     Mouse  766.0       7.0   
99 2023-04-09 00:00:00.000000000  South  Keyboard  335.0       5.0   

    Total_Revenue  
0           840.0  
1          5840.0  
2          1512